<?xml version="1.0" ?>
<testsuite name="TestHello-20220516053732" tests="5" time="0.016" failures="0" errors="1">
	<testcase classname="TestHello" name="test_hello" time="0.011"/>
	<testcase classname="TestHello" name="test_hello_hello" time="0.001"/>
	<testcase classname="TestHello" name="test_hello_name" time="0.001"/>
	<testcase classname="TestHello" name="test_new_feature" time="0.001"/>
	<testcase classname="TestHello" name="test_new_page" time="0.003">
		<error type="AssertionError" message="'404 NOT FOUND' != '200 OK'
- 404 NOT FOUND
+ 200 OK
"><![CDATA[Traceback (most recent call last):
  File "./test.py", line 34, in test_new_page
    self.assertEqual(rv.status, '200 OK')
AssertionError: '404 NOT FOUND' != '200 OK'
- 404 NOT FOUND
+ 200 OK

]]></error>
	</testcase>
	<system-out><![CDATA[]]></system-out>
	<system-err><![CDATA[]]></system-err>
</testsuite>
